### ISSUE TITLE
Alice crashes if only punctuation is input

### ISSUE THREAD

**Issue by jrha** [etattershall/toddler-chatbot#2] opened 2017-07-11 09:44 UTC
i.e. emoticons

<details>
<summary>Stack Trace</summary>

```
>>> Why?

:-(
Traceback (most recent call last):
  File "alice.py", line 96, in <module>
    print('>>> ' + reply(fulltext) + '\n')
  File "alice.py", line 53, in reply
    first_word = re.findall('^\w+', first_word)[0]
IndexError: list index out of range
```
</details>

**Comment by GRyall** [comment] 2017-07-11 09:59
This is a duplicate of #1 , though I clearly didn't give it a sensible name originally

**Comment by etattershall** [comment] 2017-07-11 10:06
Fixed only-punctuation input error and added appropriate emoticon detection and response

**Closed as completed by etattershall** 2017-07-11 10:06 UTC
